In [2]:
import pandas as pd

In [29]:
df = pd.read_csv('Dane - raport walutowy/NR3_EURUSD60.csv')

In [30]:
df['datetime_str'] = df['date'] + ' ' + df['time']
df['datetime'] = pd.to_datetime(df['datetime_str'], format='%Y.%m.%d %H:%M')

In [32]:
df = df.drop(columns=['date', 'time', 'datetime_str'])

In [33]:
df

          open     high      low    close  volume            datetime
0      1.50782  1.50937  1.50769  1.50878    1066 2009-12-03 03:00:00
1      1.50875  1.50951  1.50869  1.50923    1140 2009-12-03 04:00:00
2      1.50924  1.50927  1.50842  1.50862     884 2009-12-03 05:00:00
3      1.50865  1.50887  1.50784  1.50785    1265 2009-12-03 06:00:00
4      1.50787  1.51114  1.50759  1.51058    1695 2009-12-03 07:00:00
...        ...      ...      ...      ...     ...                 ...
64995  1.13462  1.13534  1.13206  1.13228    8809 2020-06-16 10:00:00
64996  1.13226  1.13473  1.13151  1.13364    6948 2020-06-16 11:00:00
64997  1.13363  1.13412  1.13219  1.13338    6160 2020-06-16 12:00:00
64998  1.13337  1.13350  1.13104  1.13156    5631 2020-06-16 13:00:00
64999  1.13157  1.13198  1.13088  1.13127    1595 2020-06-16 14:00:00

[65000 rows x 6 columns]

In [35]:
from sqlalchemy import create_engine

DB_PASS = 'postgres'

# Create engine (replace with your own DB credentials)
engine = create_engine(f'postgresql+psycopg2://postgres:{DB_PASS}@localhost:5432/currencies')

# Insert into table 'currencies'
df.to_sql('currencies', engine, if_exists='append', index=False)

1000